'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');const {receiptStore}=require('./receipt-store.cjs');const {submitOnce,ManusError}=require('./client.cjs');
const binding={source_sha:'a'.repeat(40),task_id:'approved-ready-1',owner:'manus-smoke',principal_type:'User',principal_login:'synthetic-founder'};
function persisted(){let rev=0,state={tasks:[{id:'existing',status:'STOP',rounds:5}]};return{load:async()=>({rev,state:structuredClone(state)}),save:async(expected,next)=>{if(expected!==rev)return false;state=structuredClone(next);rev++;return true;}};}
test('two independent adapters share one CAS receipt, existing 5-round STOP preserved',async()=>{const p=persisted(),a=receiptStore(p,binding),b=receiptStore(p,binding);let calls=0;const api={createSmoke:async()=>{calls++;return{taskId:'synthetic'};}};await Promise.all([submitOnce(api,a,'event1',{}),submitOnce(api,b,'event1',{})]);assert.equal(calls,1);const s=await p.load();assert.deepEqual(s.state.tasks,[{id:'existing',status:'STOP',rounds:5}]);assert.equal(s.state.manus_receipts.event1.value.state,'SUBMITTED');});
test('late source or different principal cannot reuse or overwrite existing receipt',async()=>{const p=persisted(),a=receiptStore(p,binding);await a.cas('event',null,{state:'CREATING'});for(const patch of [{source_sha:'b'.repeat(40)},{principal_type:'Bot'},{principal_login:'other'}]){const b=receiptStore(p,{...binding,...patch});await assert.rejects(b.get('event'),/STALE_OR_FOREIGN/);}});
test('unknown or failed persistent queue reads never mean empty queue',async()=>{const b=receiptStore({load:async()=>{throw Error('read failed');},save:async()=>true},binding);await assert.rejects(b.get('event'));});
test('uncertain receipt survives fresh adapter without repeat task creation',async()=>{const p=persisted();let n=0;const api={createSmoke:async()=>{n++;throw new ManusError('REQUEST_TIMEOUT',true);}};await assert.rejects(submitOnce(api,receiptStore(p,binding),'event',{}));const r=await submitOnce(api,receiptStore(p,binding),'event',{});assert.equal(r.state,'CREATE_UNCERTAIN');assert.equal(n,1);});
test('invalid source or principal rejected; no fabricated Bot identity fallback',()=>{for(const patch of [{source_sha:'short'},{principal_type:'Founder'},{principal_login:''}])assert.throws(()=>receiptStore(persisted(),{...binding,...patch}));});
